
# my_project/experiment.yaml
SYSTEM:
  NUM_GPUS: None
  DEVICE: 'cpu'
  NUM_WORKERS: 8
    
DATA:
  Data_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\largest_tm_lv_07071_+20/'
  Train_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\True_Label\Largest_Tumor\'
  Valid_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\True_Label\Largest_Tumor\'
  Test_dir: '/data/scratch/r098986/MIXED_HGP/HGP_Mixed_Only_Liver_07073_Windowed_Test/'

LABEL:
  label_dir: 
  label_name: 'HGP_Type'
  
TRAIN:
  lr: 0.00001
  batch_size: 1
  num_epochs: 3
  optimizer: 'SGD'
  loss: 'CrossEntropyLoss'
  Debug: True
  scheduler: True
  scheduler_name: 'WarmupCosineSchedule'
  #scheduler_param: "['step_size':20000, 'gamma': 0.1}"
  data_aug: True
  weight_decay: 0.001

VALID:
  batch_size: 1
  loss: 'CrossEntropyLoss'
  data_aug: True

TEST:
  batch_size: 1
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2
  num_channels: 1

MODEL:
  name: 'Resnet10'
  pretrained: False
  num_class: 2
  num_in_channels: 1
  dropout: 0.5
  Drop_block: False
  block_size: 5
  drop_prob: 0.9
  num_out_channels: 1

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  padding_size: (368,368,64)
  normalize: 'NormalizeIntensity'

Augmentation:
  RandZoom: (prob = 0.3, min_zoom=1.0, max_zoom=1.2)
  RandRotate: (range_z = 0.3, prob = 0.5)
  RandFlip: (prob = 0.3)
SAVE:
  save_dir: 'c:\Users\098986\Intership_CILM\Output\Resnet10\'
  save_name: 'Resnet_10_raw_0\'
  fold: '01'

WEIGHT:
  weight_dir: 'c:\Users\098986\Intership_CILM\Output\Resnet10\'

visual_im:
  visual_im: True
  visual_out_path: 'c:\Users\098986\Intership_CILM\Output\Resnet10\'
  slice: 5
