#Resnet10 3D model for training



# my_project/experiment.yaml
SYSTEM:
  NUM_GPUS: 4
  IS_CUDA: True
    
DATA:
  Data_dir: ../Data/Mixed_HGP/
  Train_dir: 1
  Valid_dir: 1
  Test_dir: 1

  
TRAIN:
  lr: 0.001
  batch_size: 3
  num_epochs: 100
  optimizer: Adam
  loss: 'CrossEntropyLoss'

VALID:
  batch_size: 3
  loss: 'CrossEntropyLoss'

TEST:
  batch_size: 3
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2
  num_channels: 3

MODEL:
  name: Resnet10
  pretrained: True
  num_classes: 2
  num_in_channels: 1
  dropout: 0.5
  num_out_channels: 1

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  resize_shape: (256,256,30)

