
# my_project/experiment.yaml
SYSTEM:
  NUM_GPUS: None
  DEVICE: 'cuda'
  NUM_WORKERS: 8
    
DATA:
  Data_dir: '/data/scratch/r098986/MIXED_HGP/tm_slices_lv_region_+3_07073_windowed/'
  Train_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/train_cv_0.csv'
  Valid_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/val_cv_0.csv'
  Test_dir: '/data/scratch/r098986/MIXED_HGP/HGP_Mixed_Only_Liver_07073_Windowed_Test/'

LABEL:
  label_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/'
  label_name: 'HGP_Type'
  
TRAIN:
  lr: 0.00001
  batch_size: 1
  num_epochs: 200
  optimizer: 'Adam'
  loss: 'CrossEntropyLoss'
  Debug: False
  #scheduler_param: "['step_size':20000, 'gamma': 0.1}"
  data_aug: True

VALID:
  batch_size: 1
  loss: 'CrossEntropyLoss'
  data_aug: True

TEST:
  batch_size: 1
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2
  num_channels: 1

MODEL:
  name: 'Resnet10'
  pretrained: False
  num_class: 2
  num_in_channels: 1
  dropout: 0.5
  num_out_channels: 1

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  resize_shape: (256,256,30)
  normalize: 'NormalizeIntensity'


SAVE:
  save_dir: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/Resnet_10_raw_0/'
  save_name: 'Resnet_10_raw_0'

WEIGHT:
  weight_dir: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/Resnet_10_raw_0/Weight/'

visual_im:
  visual_im: True
  visual_out_path: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/Resnet_10_raw_0/Visual/'

