
# my_project/experiment.yaml

###Experiment description:




SYSTEM:
  NUM_GPUS: None
  DEVICE: 'cuda'
  NUM_WORKERS: 8
    
DATA:
  Data_dir: '/data/scratch/r098986/MIXED_HGP/largest_tm_lv_07071_windowed_+20/'
  Train_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/'
  Valid_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/'
  Test_dir: '/data/scratch/r098986/MIXED_HGP/HGP_Mixed_Only_Liver_07073_Windowed_Test/'

LABEL:
  label_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/'
  label_name: 'HGP_Type'
  
TRAIN:
  lr: 0.00001
  batch_size: 1
  num_epochs: 200
  optimizer: 'SGD'
  loss: 'CrossEntropyLoss'
  Debug: False
  scheduler: True
  scheduler_name: 'WarmupCosineSchedule'
  data_aug: True
  drop_out: 0.5
  weight_decay: 0.0001

VALID:
  batch_size: 1
  loss: 'CrossEntropyLoss'
  data_aug: True

TEST:
  batch_size: 1
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2
  mask: True

MODEL:
  name: 'Resnet10'
  pretrained: False
  num_class: 2
  num_in_channels: 1
  num_out_channels: 1
  Drop_block: False
  block_size: 5
  drop_prob: 0.9

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  padding_size: (256,256,64)
  normalize: 'NormalizeIntensity'

Augmentation:
  RandZoom: (prob = 0.3, min_zoom=1.0, max_zoom=1.2)
  RandRotate: (range_z = 0.3, prob = 0.5)
  RandFlip: (prob = 0.3)
  SpatialPad: (17,17,-1)


#need to change if fold changes

SAVE:
  save_dir: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/'
  save_name: 'Resnet_10_raw_0'
  fold : '01'


WEIGHT:
  weight_dir: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/'
#need to change if fold changes

visual_im:
  visual_im: True
  visual_out_path: '/data/scratch/r098986/MIXED_HGP/Results/Resnet10/'
  slice: 5
  

WarmupCosineSchedule:
  warmup_steps: 600
  t_total: 2000