
# my_project/experiment.yaml
SYSTEM:
  NUM_GPUS: None
  DEVICE: 'cpu'
  NUM_WORKERS: 2
    
    
DATA:
  Data_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\Mixed_HGP_lv_with_tumor_07073_Windowed\'
  Train_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\True_Label\train_cv_0.csv'
  Valid_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\True_Label\val_cv_0.csv'
  Test_dir: '/data/scratch/r098986/MIXED_HGP/HGP_Mixed_Only_Liver_07073_Windowed_Test/'

LABEL:
  label_dir: 'c:\Users\098986\Intership_CILM\Data\Mixed_HGP\True_Label\scans_used_all_info.csv'
  label_name: 'HGP_Type'
  
TRAIN:
  lr: 0.001
  batch_size: 1
  num_epochs: 10
  optimizer: 'Adam'
  loss: 'CrossEntropyLoss'
  Debug: False 
  #scheduler_param: "['step_size':20000, 'gamma': 0.1}"
  data_aug: True

VALID:
  batch_size: 1
  loss: 'CrossEntropyLoss'
  data_aug: True

TEST:
  batch_size: 1
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2
  num_channels: 3

MODEL:
  name: 'SACNN'
  pretrained: False
  num_class: 2
  num_in_channels: 1
  dropout: 0.5
  num_out_channels: 1

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  resize_shape: (256,256,30)
  normalize: 'NormalizeIntensity'


SAVE:
  save_dir: 'c:\Users\098986\Intership_CILM\Output\SACNN\Test_local\'
  save_name: 'Test_local'
  fold : '01'

WEIGHT:
  weight_dir: 'c:\Users\098986\Intership_CILM\Output\SACNN\Test_local\Weight\'

visual_im:
  visual_im: True
  visual_out_path: 'c:\Users\098986\Intership_CILM\Output\SACNN\Test_local\Visual\'

