
# my_project/experiment.yaml
SYSTEM:
  NUM_GPUS: None
  DEVICE: 'cuda'
  NUM_WORKERS: 6
    
DATA:
  Data_dir: '/data/scratch/r098986/tm_slices_lv_region_07073_windowed/'
  Train_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/train_cv_3.csv'
  Valid_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/val_cv_3.csv'
  Test_dir: '/data/scratch/r098986/MIXED_HGP/HGP_Mixed_Only_Liver_07073_Windowed_Test/'

LABEL:
  label_dir: '/data/scratch/r098986/MIXED_HGP/True_Label/'
  label_name: 'HGP_Type'

LOSS:
  loss_mode: 'classification'
  loss_name: 'CrossEntropyLoss'

TRAIN:
  lr: 0.00001
  batch_size: 2
  num_epochs: 300
  optimizer: 'Adam'
  loss: 'CrossEntropyLoss'
  Debug: False
  scheduler: True
  scheduler_name: 'WarmupCosineSchedule'

  data_aug: True
  drop_out: 0.5

VALID:
  batch_size: 1
  loss: 'CrossEntropyLoss'
  data_aug: True

TEST:
  batch_size: 1
  loss: 'CrossEntropyLoss'

DATASET:
  WeightedRandomSampler: True
  num_classes: 2


MODEL:
  name: 'SwingTransformer'
  pretrained: False
  num_class: 2
  num_in_channels: 1
  num_out_channels: 1
  v2: True

LOG:
  log_dir: ./logs
  log_file: log.txt

Preprocess:
  padding_size: (256,256,64)

  normalize: 'NormalizeIntensity'


Augmentation:
  SpatialPad: (256,256,64)
  CenterSpatialCrop: (256,256,64)
  Resize: (256,256,64)
  RandZoom: (prob = 0.3, min_zoom=1.0, max_zoom=1.2)
  RandRotate: (range_z = 0.3, prob = 0.5)
  RandFlip: (prob = 0.3)
  RandSpatialCrop: (256,256,64)

SAVE:
#need to change if exp changes
  save_dir: '/data/scratch/r098986/MIXED_HGP/Results/SwingTransformer/SWTS_Exp_0/'
  save_name: 'SwingTransformer'
  fold : '04'

WEIGHT:
  weight_dir: '/data/scratch/r098986/MIXED_HGP/Results/SwingTransformer/SWTS_Exp_0/04/Weight/'

#need to change if fold changes
visual_im:
  visual_im: True
  visual_out_path: '/data/scratch/r098986/MIXED_HGP/Results/SwingTransformer/SWTS_Exp_0/04/Visual/'
  slice: 32